# Dependencies
#markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Jeet Majumdar
tagline:          'Keep it coded'
description:      'A place for the noobs!'
url:              https://jeet-majumdar.github.io/live//
baseurl:          '/live//' 

author:
  name:           'Jeet'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Jeet-Majumdar

plugins:
        - jekyll-gist
        - jekyll-paginate         
